version: "3.8"
services:
    mongoDB:
        image: mongo:4.4
        container_name: mongoDB
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
          - mongoData:/data
          - mongoData:/data/configdb
          - mongoData:/data/db
        networks:
          - mongoNetwork
        ports:
          - ${MONGO_EXPOSE_PORT}:${MONGO_DOCKER_PORT}
        
    mongoExpress:
        image: mongo-express:0.54.0
        container_name: mongExpress
        # restart: unless-stopped
        environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
          - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
          # - ME_CONFIG_MONGODB_URL=mongoDB://root:root@mongo:27017/?authSource=admin
          - ME_CONFIG_MONGODB_URL="mongoDB://localhost:${MONGO_DOCKER_PORT}"
          - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME}
          - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
          - ME_CONFIG_MONGODB_PORT=${MONGO_DOCKER_PORT}
        volumes:
          - mongoExpressData:/data
        depends_on:
          - mongoDB
        networks:
          - mongoNetwork
        ports:
          - "${MONGO_EXPRESS_EXPOSE_PORT}:${MONGO_EXPRESS_DOCKER_PORT}"
volumes:
  mongoData:
  mongoExpressData:
networks:
  mongoNetwork:
 