# version: "3.7"

# services:
#   mongoDB:
#     container_name: mongoDB
#     image: mongo:4.4

#     ports:
#       - 27017:27017
#     # restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: root
#     volumes:
#       - mongoDATA1:/data/configdb
#       - mongoDATA2:/data/db
#     networks:
#       - mongoNetwork
#   # mongoexpress:
#   #   image: mongo-express:0.54.0
#   #   restart: unless-stopped
#   #   depends_on:
#   #     - mongoDB
#   #   ports:
#   #     - "8081:8081"
#   #   links:
#   #     - mongoDB
#   #   environment:
#   #     # ME_CONFIG_MONGODB_URL: mongoDB://root:root@mongo:27017/"
#   #     ME_CONFIG_MONGODB_SERVER: mongoDB
#   #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
#   #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
#   #   networks:
#   #     - mongoNetwork
# networks:
#   mongoNetwork:
#     # driver: bridge
# volumes:
#   mongoDATA1:
#   mongoDATA2:
 

version: "3.8"
services:
    mongoDB:
        image: mongo:4.4
        container_name: mongoDB
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
          - mongoDATA1:/data/configdb
          - mongoDATA2:/data/db
        networks:
          - mongoNetwork
        ports:
          - 27017:27017
        
    mongoExpress:
        image: mongo-express:0.54.0
        container_name: mongExpress
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongodb
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_MONGODB_ADMINUSERNAME=root
          - ME_CONFIG_MONGODB_ADMINPASSWORD=root
          - ME_CONFIG_BASICAUTH_USERNAME=root
          - ME_CONFIG_BASICAUTH_PASSWORD=root
        volumes:
          - mongoDATA1:/data/configdb
          - mongoDATA2:/data/db
        depends_on:
          - mongoDB
        networks:
          - mongoNetwork
        ports:
          - 8081:8081
       
volumes:
  mongoDATA1:
  mongoDATA2:
networks:
  mongoNetwork:
 