version: '3'
services:
  sonarQubeCore:
    container_name: sonarQubeCore
    image: sonarqube:9.9.2-community
    ports:
      - "5001:9000"
    networks:
      - sonarNetworkCore
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://${SONARQUBE_DB_HOST}:${SONARQUBE_DB_PORT}/${SONARQUBE_DB_NAME}
      - SONARQUBE_JDBC_USERNAME=${SONARQUBE_DB_USERNAME}
      - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_DB_PASSWORD}
    volumes:
      - sonarQubeVolumeCore:/opt/sonarqube/data
      - sonarQubeVolumeCore:/opt/sonarqube/extensions
      - sonarQubeVolumeCore:/opt/sonarqube/logs
      - sonarQubeVolumeCore:/opt/sonarqube/temp
    network_mode: bridge
networks:
  sonarNetworkCore:
    driver: bridge

volumes:
  sonarQubeVolumeCore:
